// Generates src/lib/analytics/world-dots.ts: the land of the world as a grid of dots, for the
// visitor map. Run once; the output is committed.
//
//   npm pack world-atlas@2.0.2 && tar xzf world-atlas-2.0.2.tgz
//   node scripts/world-dots.mjs package/land-50m.json
//
// Land outlines: Natural Earth (public domain), via world-atlas (ISC).

import { readFileSync, writeFileSync } from "node:fs";

const STEP = 2; // degrees between dots
const NORTH = 84; // top of the grid (skips nothing inhabited)
const SOUTH = -58; // bottom of the grid (leaves out Antarctica)

const topology = JSON.parse(readFileSync(process.argv[2], "utf8"));
const { scale, translate } = topology.transform;

// Decode the delta-encoded, quantized arcs into [lon, lat] points.
const arcs = topology.arcs.map((arc) => {
  let x = 0;
  let y = 0;
  return arc.map(([dx, dy]) => {
    x += dx;
    y += dy;
    return [x * scale[0] + translate[0], y * scale[1] + translate[1]];
  });
});
const ring = (indexes) =>
  indexes.flatMap((index, position) => {
    const points = index < 0 ? arcs[~index].slice().reverse() : arcs[index];
    return position === 0 ? points : points.slice(1);
  });

const rings = [];
for (const geometry of topology.objects.land.geometries) {
  const polygons = geometry.type === "Polygon" ? [geometry.arcs] : geometry.arcs;
  for (const polygon of polygons) for (const indexes of polygon) rings.push(ring(indexes));
}

// Even-odd ray casting across every ring: inside land, outside holes.
function onLand(lon, lat) {
  let inside = false;
  for (const points of rings) {
    for (let i = 0, j = points.length - 1; i < points.length; j = i++) {
      const [xi, yi] = points[i];
      const [xj, yj] = points[j];
      if (yi > lat !== yj > lat && lon < ((xj - xi) * (lat - yi)) / (yj - yi) + xi)
        inside = !inside;
    }
  }
  return inside;
}

const columns = Math.round(360 / STEP);
const rows = Math.round((NORTH - SOUTH) / STEP);
// Each row as run lengths, alternating sea and land, starting with sea.
const encoded = [];
let dots = 0;
for (let row = 0; row < rows; row++) {
  const lat = NORTH - (row + 0.5) * STEP;
  const runs = [];
  let current = false;
  let length = 0;
  for (let column = 0; column < columns; column++) {
    const land = onLand(-180 + (column + 0.5) * STEP, lat);
    if (land) dots++;
    if (land === current) length++;
    else {
      runs.push(length);
      current = land;
      length = 1;
    }
  }
  runs.push(length);
  encoded.push(runs.map((run) => run.toString(36)).join("."));
}

writeFileSync(
  new URL("../src/lib/analytics/world-dots.ts", import.meta.url),
  `// Generated by scripts/world-dots.mjs from Natural Earth land outlines (public domain). Do not edit.

/** Degrees between dots, and the latitudes the grid spans (equirectangular). */
export const WORLD_GRID = { step: ${STEP}, north: ${NORTH}, south: ${SOUTH}, columns: ${columns}, rows: ${rows} } as const;

/** One string per row: run lengths in base 36, alternating sea and land, starting with sea. */
export const WORLD_ROWS: readonly string[] = ${JSON.stringify(encoded)};
`,
);
console.log(`${dots} dots, ${columns} x ${rows}`);
